[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cuSZp Documentation"
authors = [{name = "Yafan Huang", email = "yafan-huang@uiowa.edu"}]
dynamic = ["version", "description"]
